name: Release Go Binary

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel
        goos: [windows, darwin, linux]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -ldflags "-X main.Version=${{ env.APP_VERSION }}"




    # - uses: wangyoucao577/go-release-action@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     goos: ${{ matrix.goos }}
    #     goarch: ${{ matrix.goarch }}
    #     goversion: "latest"
    #     binary_name: "itunesexport"
    #     build_flags: -v
    #     ldflags: -X "main.Version=${{ env.APP_VERSION }}"
    #     extra_files: README.md
